import Icons from '@/components/Icons';
import Reviewimg1 from '../assets/images/review-img-1.png';
import Hero from '../assets/images/blogs-hero-img.avif';
import Blogimg1 from '@/assets/images/blogs-img-1.avif';
import Risponse from '../assets/images/latest-news-section-mini-img-1.jpeg';
import Relatedimg1 from '../assets/images/The-latest-news-section-img-3.jpeg';
import Relatedimg2 from '../assets/images/blog-related-img.webp';
import Relatedimg3 from '../assets/images/The-latest-news-section-img-2.jpeg';
import Relatedimg4 from '../assets/images/The-latest-news-section-img-4.jpeg';
import TheFooter from '@/components/TheFooter';
import { ReactElement } from 'react';
import RootLayout from '@/layouts/RootLayout';
import Head from 'next/head'
const Blogs = () => {
    return (
        <>
            <Head>
                <title>Ciseco | Bolg</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section className="py-4">
                <div className="container">
                    <div className="row justify-content-center">
                        <div className="col-md-8">
                            <div>
                                <p className='m-0 d-flex align-items-center gap-2 pb-2'>
                                    <span className='fs-12 special-offer-step-section3'>Traveler</span>
                                </p>
                                <h2 className='fw-semibold'>Keep up the spirit of the desire to travel around the world</h2>
                                <p>Were&#39; an online magazine dedicated to covering the best in international product design. We started as a little blog back in 2002 covering student work and over time</p>
                            </div>
                            <hr />
                            <div className="d-flex justify-content-between align-items-center">
                                <div>
                                    <div className='review-img-wrapper d-flex align-items-center gap-2'>
                                        <div>
                                            <img src={Reviewimg1.src} alt="review" className='img-fluid' />
                                        </div>
                                        <div>
                                            <p className='m-0 fs-14 fw-semibold'>Fones Mimi</p>
                                            <p className='m-0 fs-12'>May 20, 2021·6 min read</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="blogs-social-icons">
                                    <div className='d-flex gap-2'>
                                        <Icons.Facebook />
                                        <Icons.Twitter />
                                        <Icons.Youtube />
                                        <Icons.Telegram />
                                    </div>
                                </div>
                            </div>
                            <div className='pt-3'>
                                <img src={Hero.src} alt="hero" className='img-fluid rounded-4' />
                            </div>
                        </div>
                    </div>
                    <div className="row justify-content-center mt-4">
                        <div className="col-md-8">
                            <div className='description'>
                                <div>
                                    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure vel officiis ipsum placeat itaque neque dolorem modi perspiciatis dolor distinctio veritatis sapiente, minima corrupti dolores necessitatibus suscipit accusantium dignissimos culpa cumque.</p>
                                    <p>It is a long established fact that a <span className='fw-semibold text-black'>reader</span> will be distracted by the readable content of a page when looking at its<span className='fw-semibold text-black'> layout.</span>  The point of using Lorem Ipsum is that it has a more-or-less normal <a href="" className='text-black fw-semibold'>distribution of letters.</a></p>
                                </div>
                                <ol className='flex-column gap-2 d-flex'>
                                    <li>We want everything to look good out of the box.</li>
                                    <li>Really just the first reason, that's the whole point of the plugin.</li>
                                    <li>Here's a third pretend reason though a list with three items looks more realistic than a list with two items.</li>
                                </ol>
                                <div className='pt-3'>
                                    <h3 className='fw-semibold pb-2'>Typography should be easy</h3>
                                    <p>So that's a header for you — with any luck if we've done our job correctly that will look pretty reasonable.</p>
                                    <p>Something a wise person once told me about typography is:</p>
                                    <p className='fst-italic fw-semibold my-3 fs-5'>&#34;Typography is pretty important if you don't want your stuff to look like trash. Make it good then it won't be bad.&#34;</p>
                                    <p>It's probably important that images look okay here by default as well:</p>
                                </div>
                                <div className='blog-img-wrapper'>
                                    <img src={Blogimg1.src} alt="blog img" className='img-fluid rounded-4' />
                                    <p className='text-secondary pt-2'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure vel officiis ipsum placeat itaque neque dolorem modi perspiciatis dolor distinctio veritatis sapiente</p>
                                </div>
                                <div>
                                    <p>Now I'm going to show you an example of an unordered list to make sure that looks good, too:</p>
                                    <ul className='d-flex flex-column gap-2'>
                                        <li>So here is the first item in this list.</li>
                                        <li>In this example we're keeping the items short.</li>
                                        <li>Later, we'll use longer, more complex list items.</li>
                                    </ul>
                                    <p>And that's the end of this section.</p>
                                </div>
                                <div className='mt-4'>
                                    <h3 className='fw-semibold'>Code should look okay by default.</h3>
                                    <p>I think most people are going to use highlight.js or Prism or something if they want to style their code blocks but it wouldn't hurt to make them look okay out of the box, even with no syntax highlighting.</p>
                                    <p>What I've written here is probably long enough, but adding this final sentence can't hurt.</p>
                                    <p>Hopefully that looks good enough to you.</p>
                                </div>
                                <div>
                                    <h4 className='fw-semibold'>We still need to think about stacked headings though.</h4>
                                    <p className='fw-semibold'>Let's make sure we don't screw that up with &#96;h4&#96; elements, either.</p>
                                    <p>Phew, with any luck we have styled the headings above this text and they look pretty good.</p>
                                    <p className='py-3'>Let's add a closing paragraph here so things end with a decently sized block of text. I can't explain why I want things to end that way but I have to assume it's because I think things will look weird or unbalanced if there is a heading too close to the end of the document.</p>
                                    <p>What I've written here is probably long enough, but adding this final sentence can't hurt.</p>
                                </div>
                                <div className='d-flex flex-row gap-2'>
                                    <button className='btn-outline-light'>Hotdog (22)</button>
                                    <button className='btn-outline-light'>Car (22)</button>
                                    <button className='btn-outline-light'>Vue (22)</button>
                                    <button className='btn-outline-light'>Vue (22)</button>
                                </div>
                                <hr />
                                {/* risponse ********************/}
                                <div className='risponse'>
                                    <div className='d-flex align-items-center gap-3'>
                                        <img src={Risponse.src} alt="risponse" className='img-fluid' />
                                        <div>
                                            <p className='text-secondary fs-12 m-0'>Written By</p>
                                            <h6 className='py-1 m-0 fw-semibold'>Fones Mimi</h6>
                                            <p className='text-secondary'>Theres&#39; no stopping the tech giant. Apple now opens its 100th store in China.Theres&#39; no stopping the tech giant. <a href="" className='text-blue text-decoration-none fw-semibold'>Readmore</a></p>
                                        </div>
                                    </div>
                                    <div className="form-floating mt-3">
                                        <textarea className="form-control rounded-3" placeholder="Leave a comment here" id="floatingTextarea" style={{ height: 150 }} ></textarea>

                                    </div>
                                    <div className='mt-3 d-flex align-items-center gap-3'>
                                        <button className='btn btn-primary rounded-pill fs-6 py-2'>Submit</button>
                                        <button className='btn btn-outline-light rounded-pill py-2 text-secondary'>Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {/* Related photos ********/}
            <section className='py-4'>
                <div className="container">
                    <div className="row">
                        <div className="col-md-12">
                            <div className='section-heading'>
                                <h2>Related posts</h2>
                            </div>
                        </div>
                    </div>
                    <div className="row gy-4 justify-content-start justify-content-md-center">
                        <div className="col-sm-6 col-md-4 col-lg-3">
                            <div className='position-relative card-shadow-wrapper overflow-hidden rounded-4'>
                                <img src={Relatedimg1.src} alt="Relatedimg1" className='img-fluid related-img' />
                                <div className='blog-card-content p-2'>
                                    <p className='m-0 d-flex align-items-center gap-2 pb-2'>
                                        <span className='fs-12 special-offer-step-section2'>Categories</span>
                                    </p>
                                    <div className='text-white'>
                                        <p className='fw-semibold fw-semibold'>in arcu cursus viverra nibh cras pulvinar mattis...</p>
                                        <div className='d-flex gap-2'>
                                            <span className='fs-12'>Derick Hub</span>
                                            <span> · </span>
                                            <span className='fs-12'>May 20, 2021</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-sm-6 col-md-4 col-lg-3">
                            <div className='position-relative card-shadow-wrapper overflow-hidden rounded-4'>
                                <img src={Relatedimg2.src} alt="Relatedimg1" className='img-fluid related-img' />
                                <div className='blog-card-content p-2'>
                                    <p className='m-0 d-flex align-items-center gap-2 pb-2'>
                                        <span className='fs-12 special-offer-step-section2'>Categories</span>
                                    </p>
                                    <div className='text-white'>
                                        <p className='fw-semibold fw-semibold'>in arcu cursus viverra nibh cras pulvinar mattis...</p>
                                        <div className='d-flex gap-2'>
                                            <span className='fs-12'>Moke Orr</span>
                                            <span> · </span>
                                            <span className='fs-12'>May 20, 2021</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-sm-6 col-md-4 col-lg-3">
                            <div className='position-relative card-shadow-wrapper overflow-hidden rounded-4'>
                                <img src={Relatedimg3.src} alt="Relatedimg1" className='img-fluid related-img' />
                                <div className='blog-card-content p-2'>
                                    <p className='m-0 d-flex align-items-center gap-2 pb-2'>
                                        <span className='fs-12 special-offer-step-section2'>Categories</span>
                                    </p>
                                    <div className='text-white'>
                                        <p className='fw-semibold fw-semibold'>in arcu cursus viverra nibh cras pulvinar mattis...</p>
                                        <div className='d-flex gap-2'>
                                            <span className='fs-12'>Belinda Rer</span>
                                            <span> · </span>
                                            <span className='fs-12'>May 215, 2020</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-sm-6 col-md-4 col-lg-3">
                            <div className='position-relative overflow-hidden card-shadow-wrapper rounded-4'>
                                <div className='related-img-wrapper'>
                                    <img src={Relatedimg4.src} alt="Relatedimg1" className='img-fluid related-img' />
                                </div>
                                <div className='blog-card-content p-2'>
                                    <p className='m-0 d-flex align-items-center gap-2 pb-2'>
                                        <span className='fs-12 special-offer-step-section2'>Categories</span>
                                    </p>
                                    <div className='text-white'>
                                        <p className='fw-semibold fw-semibold'>in arcu cursus viverra nibh cras pulvinar mattis...</p>
                                        <div className='d-flex gap-2'>
                                            <span className='fs-12'>Malacal Cey</span>
                                            <span> · </span>
                                            <span className='fs-12'>May 10, 2022</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}


Blogs.getLayout = function getLayout(page: ReactElement) {
    return (
        <RootLayout>
            {page}
        </RootLayout>
    )
}

export default Blogs;