import Icons from "@/components/Icons"
import RootLayout from "@/layouts/RootLayout"
import Link from "next/link"
import { ReactElement } from "react"
import Hoodie from '../assets/images/trending-section-hoddie.png';
import Cap from '../assets/images/trending-section-cap.png';
import Purse from '../assets/images/trending-section-purse.png';
import Head from 'next/head'

const Checkout = () => {
    return (
        <>
            <Head>
                <title>Ciseco | Checkout</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section className="py-4">
                <div className="container">
                    <div className="row">
                        <div className="col-md-12">
                            <div className="section-heading">
                                <h1 className="text-center text-md-start fw-bold">Checkout</h1>
                                <nav aria-label="breadcrumb">
                                    <ol className="breadcrumb justify-content-center justify-content-start">
                                        <li className="breadcrumb-item"><Link href="/" className="text-decoration-none text-black">Homepage</Link></li>

                                        <li className="breadcrumb-item"><Link href="/" className="text-decoration-none text-black">Clothing Categories</Link></li>

                                        <li className="breadcrumb-item active text-black text-decoration-underline" aria-current="page">Checkout</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div className="row mt-4 justify-content-between">
                        {/***************** Left-Side ****************/}
                        <div className="col-md-6 p-0">
                            {/******************** Card-1 *******************/}
                            <div className="card rounded-3">
                                <div className="d-flex align-items-center p-3 justify-content-between border-bottom pb-3">
                                    <div className="d-flex gap-3 flex-column flex-md-row">
                                        <div>
                                            <Icons.Account />
                                        </div>

                                        <div>
                                            <p className="m-0 pb-1 d-flex align-items-center gap-2">
                                                <span>Contact Info</span>
                                                <Icons.Check />
                                            </p>
                                            <h6 className="fw-semibold">Enrico Smith+855 - 666 - 7744</h6>
                                        </div>
                                    </div>
                                    <div>
                                        <button className="btn btn-outline-info">Change</button>
                                    </div>
                                </div>
                                <div className="p-3">
                                    <div className="d-flex justify-content-between flex-md-row flex-column ">
                                        <h6>Contact Information</h6>
                                        <p>Do not have an account? <a href="" className="text-decoration-none text-blue">Log in</a></p>
                                    </div>
                                    <form>
                                        <label htmlFor="exampleInputPassword1" className="form-label fw-medium">Mobile Number</label>
                                        <div className="input-group mb-3 w-100">
                                            <button className="btn input-edit btn-outline-secondary contact-btn-wrapper rounded-start-4 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">+91</button>
                                            <ul className="dropdown-menu">
                                                <li className="dropdown-item">+85</li>
                                                <li className="dropdown-item">+25</li>
                                                <li className="dropdown-item">+51</li>
                                                <li className="dropdown-item">+22</li>
                                            </ul>
                                            <input type="text" className="rounded-end-4 form-control" aria-label="Text input with dropdown button" />
                                        </div>
                                        <div className="mb-3">
                                            <label htmlFor="exampleInputPassword1" className="form-label fw-medium">Email Address</label>
                                            <input type="email" className="form-control rounded-4" id="exampleInputPassword1" />
                                        </div>
                                        <div className="mb-3 form-check d-flex gap-2 align-items-center">
                                            <input type="checkbox" className="form-check-input checkout-checkbox" id="exampleCheck1" />
                                            <label className="form-check-label" htmlFor="exampleCheck1">Check me out</label>
                                        </div>
                                        <div className="mt-4 d-flex gap-2 align-items-center flex-column flex-md-row">
                                            <button type="submit" className="btn btn-primary rounded-pill">Save and next to Shipping</button>
                                            <button className="btn btn-outline-dark border-0 rounded-pill">Cancel</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            {/******************** Card-2 *******************/}
                            <div className="card rounded-3 mt-4">
                                <div className="d-flex align-items-center p-3 justify-content-between border-bottom pb-3">
                                    <div className="d-flex gap-3 flex-column flex-md-row">
                                        <div>
                                            <Icons.Dubblearrow />
                                        </div>

                                        <div>
                                            <p className="m-0 pb-1 d-flex align-items-center gap-2">
                                                <span>SHIPPING ADDRESS</span>
                                                <Icons.Check />
                                            </p>
                                            <h6 className="fw-semibold">St. Paul's Road, Norris, SD 57560, Dakota, USA</h6>
                                        </div>
                                    </div>
                                    <div>
                                        <button className="btn btn-outline-info">Change</button>
                                    </div>
                                </div>
                                <div className="p-3">
                                    <div className="row mt-2">
                                        {/*********** First Name **********/}
                                        <div className="col-md-6">
                                            <form>
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputEmail1" className="form-label fw-medium">First Name</label>
                                                    <input type="text" className="form-control rounded-4" id="exampleInputEmail1" defaultValue={"cole"} aria-describedby="emailHelp" />
                                                </div>
                                            </form>
                                        </div>
                                        {/*********** Last Name **********/}
                                        <div className="col-md-6">
                                            <form>
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputEmail1" className="form-label fw-medium">Last Name</label>
                                                    <input type="text" className="form-control rounded-4" id="exampleInputEmail1" defaultValue={"Enrico "} aria-describedby="emailHelp" />
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <div className="row mt-2">
                                        {/*********** Address **********/}
                                        <div className="col-md-8">
                                            <form>
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputEmail1" className="form-label fw-medium">Address</label>
                                                    <input type="text" className="form-control rounded-4" id="exampleInputEmail1" defaultValue={"123, Dream Avenue, USA"} aria-describedby="emailHelp" />
                                                </div>
                                            </form>
                                        </div>
                                        {/*********** Apt, Suite * **********/}
                                        <div className="col-md-4">
                                            <form>
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputEmail1" className="form-label fw-medium">Apt, Suite *</label>
                                                    <input type="text" defaultValue={'55U - DD5 '} className="form-control rounded-4" id="exampleInputEmail1" aria-describedby="emailHelp" />
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <div className="row mt-2">
                                        {/*********** City **********/}
                                        <div className="col-md-6">
                                            <form>
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputEmail1" className="form-label fw-medium">City</label>
                                                    <input type="text" className="form-control rounded-4" id="exampleInputEmail1" defaultValue={"Norris"} aria-describedby="emailHelp" />
                                                </div>
                                            </form>
                                        </div>
                                        {/*********** Country **********/}
                                        <div className="col-md-6">
                                            <form>
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputEmail1" className="form-label fw-medium">Country</label>
                                                    <select className="form-control rounded-4" id="country's" name="country's">
                                                        <option value="Canada">Canada</option>
                                                        <option value="China">China</option>
                                                        <option value="Laos">Laos</option>
                                                        <option value="India">India</option>
                                                    </select>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    <div className="row mt-2">
                                        <div className="col-md-6">
                                            {/*********** State * **********/}
                                            <form>
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputEmail1" className="form-label fw-medium">State/Province</label>
                                                    <input type="text" className="form-control rounded-4" id="exampleInputEmail1" defaultValue={"texas"} aria-describedby="emailHelp" />
                                                </div>
                                            </form>
                                        </div>
                                        {/*********** Postal Code * **********/}
                                        <div className="col-md-6">
                                            <form>
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputEmail1" className="form-label fw-medium">Postal code</label>
                                                    <input type="text" className="form-control rounded-4" id="exampleInputEmail1" defaultValue={"2500"} aria-describedby="emailHelp" />
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                    {/*********** Address Type * **********/}
                                    <div className="row mt-2">
                                        <p className="fw-medium">Address type</p>
                                        <div className="col-md-6">
                                            <div className="d-flex gap-2">
                                                <input type="radio" className="checkout-radio-button" id="html" name="fav_language" value="HTML" />
                                                <label htmlFor="html">Home</label>
                                            </div>
                                        </div>
                                        <div className="col-md-6">
                                            <div className="d-flex gap-2">
                                                <input type="radio" className="checkout-radio-button" id="css" name="fav_language" value="CSS" />
                                                <label htmlFor="css">Office</label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {/******************** Card-3 *******************/}
                            <div className="card rounded-3 mt-4">
                                <div className="d-flex align-items-center p-3 justify-content-between border-bottom pb-3">
                                    <div className="d-flex gap-3 flex-column flex-md-row">
                                        <div>
                                            <Icons.Card />
                                        </div>

                                        <div>
                                            <p className="m-0 pb-1 d-flex align-items-center gap-2">
                                                <span>Payment Method</span>
                                                <Icons.Check />
                                            </p>
                                            <h6 className="fw-semibold">Google / Apple Walletxxx-xxx-xx55</h6>
                                        </div>
                                    </div>
                                    <div>
                                        <button className="btn btn-outline-info">Change</button>
                                    </div>
                                </div>
                                <div className="p-3">
                                    <div className="d-flex gap-3 align-items-center mb-4">
                                        <div className="border border-secondary p-2 rounded-3">
                                            <Icons.Debitcard />
                                        </div>
                                        <p className="m-0">Debit / Credit Card</p>
                                    </div>
                                    <form>
                                        {/***********  Card Number **********/}
                                        <div className="mb-3">
                                            <label htmlFor="exampleInputEmail1" className="form-label">Card Number</label>
                                            <input type="text" className="form-control rounded-4" id="exampleInputEmail1" aria-describedby="emailHelp " />
                                        </div>
                                        {/*********** Name on Card **********/}
                                        <div className="mb-3">
                                            <label htmlFor="exampleInputEmail1" className="form-label">Name on Card</label>
                                            <input type="text" className="form-control rounded-4" id="exampleInputEmail1" aria-describedby="emailHelp " />
                                        </div>
                                        <div className="row">
                                            {/*********** Expiration Date **********/}
                                            <div className="col-md-8">
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputPassword1" className="form-label">Expiration date (MM/YY)</label>
                                                    <input type="email" placeholder="MM/YY" className="form-control rounded-4" id="exampleInputPassword1" />
                                                </div>
                                            </div>
                                            {/*********** CVC **********/}
                                            <div className="col-md-4">
                                                <div className="mb-3">
                                                    <label htmlFor="exampleInputPassword1" className="form-label">CVC</label>
                                                    <input type="email" placeholder="CVC" className="form-control rounded-4" id="exampleInputPassword1" />
                                                </div>
                                            </div>
                                        </div>
                                        <div className="mt-4 d-flex gap-2 align-items-center flex-column flex-md-row">
                                            <button type="submit" className="btn btn-primary rounded-pill fs-6">Save and next to Shipping</button>
                                            <button className="btn btn-outline-dark border-0 rounded-pill">Cancel</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div className="col-1 p-0">
                            <div className="d-flex flex-column align-items-center h-100">
                                <div className="divider-checkout h-100">

                                </div>
                            </div>
                        </div>
                        {/***************** Left-Side ****************/}
                        <div className="col-md-5 p-0">
                            <div className="sticky-top bg-light z-1 p-3">
                                <div className="row mb-3">
                                    <div className="col-md-12">
                                        <h5 className="fw-semibold">Order Summary</h5>
                                    </div>
                                </div>
                                {/************* Card-1 ************/}
                                <div className="row d-flex flex-md-row flex-column">
                                    <div className="col-md-12 col-lg-3">
                                        <div className="discover-bg-blue rounded-4 text-center">
                                            <img src={Hoodie.src} alt="hoodie" className="img-fluid" />
                                        </div>
                                    </div>
                                    <div className="col-md-12 col-lg-9">
                                        <div className="p-3">
                                            <div>
                                                <div className="d-flex justify-content-between flex-column flex-lg-row">
                                                    <div className="title pb-2">
                                                        <p className="fw-semibold m-0">Rey Nylon Backpack</p>
                                                    </div>
                                                    <div>
                                                        <p className="text-green m-0 text-lg-start text-center">$74.00</p>
                                                    </div>
                                                </div>
                                                <div className="d-lg-flex gap-2 align-items-center d-none">
                                                    <div className="d-flex gap-1 align-items-center">
                                                        <Icons.Color />
                                                        <span className="fs-14">Black</span>
                                                        <span> | </span>
                                                    </div>
                                                    <div className="d-flex gap-1 align-items-center">
                                                        <Icons.Size />
                                                        <span className="fs-14">2XL</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="d-flex justify-content-between align-items-center mt-3">
                                                <div className="counter-wrapper d-flex bg-white">
                                                    <button className="rounded-circle border-0">&#8722;</button>
                                                    <input type="text" defaultValue={"1"} className="bg-white" />
                                                    <button className="rounded-circle border-0">&#43;</button>
                                                </div>
                                                <div>
                                                    <Link href={""} className="text-decoration-none text-blue">Remove</Link>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <hr className="my-5" />
                                {/************* Card-2 ************/}
                                <div className="row d-flex flex-md-row flex-column">
                                    <div className="col-md-12 col-lg-3">
                                        <div className="discover-bg-blue rounded-4 text-center">
                                            <img src={Cap.src} alt="hoodie" className="img-fluid" />
                                        </div>
                                    </div>
                                    <div className="col-md-12 col-lg-9">
                                        <div className="p-3">
                                            <div>
                                                <div className="d-flex justify-content-between flex-column flex-lg-row">
                                                    <div className="title pb-2">
                                                        <p className="fw-semibold m-0">Waffle Knit Beanie</p>
                                                    </div>
                                                    <div>
                                                        <p className="text-green m-0 text-lg-start text-center">$132.00</p>
                                                    </div>
                                                </div>
                                                <div className="d-lg-flex gap-2 align-items-center d-none">
                                                    <div className="d-flex gap-1 align-items-center">
                                                        <Icons.Color />
                                                        <span className="fs-14">Black</span>
                                                        <span> | </span>
                                                    </div>
                                                    <div className="d-flex gap-1 align-items-center">
                                                        <Icons.Size />
                                                        <span className="fs-14">2XL</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="d-flex justify-content-between align-items-center mt-3">
                                                <div className="counter-wrapper d-flex bg-white">
                                                    <button className="rounded-circle border-0">&#8722;</button>
                                                    <input type="text" defaultValue={"1"} className="bg-white" />
                                                    <button className="rounded-circle border-0">&#43;</button>
                                                </div>
                                                <div>
                                                    <Link href={""} className="text-decoration-none text-blue">Remove</Link>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <hr className="my-5" />
                                {/************* Card-3 ************/}
                                <div className="row d-flex flex-md-row flex-column">
                                    <div className="col-md-12 col-lg-3">
                                        <div className="discover-bg-blue rounded-4 text-center">
                                            <img src={Purse.src} alt="hoodie" className="img-fluid" />
                                        </div>
                                    </div>
                                    <div className="col-md-12 col-lg-9">
                                        <div className="p-3">
                                            <div>
                                                <div className="d-flex justify-content-between flex-column flex-lg-row">
                                                    <div className="title pb-2">
                                                        <p className="fw-semibold m-0">Travel Pet Carrier</p>
                                                    </div>
                                                    <div>
                                                        <p className="text-green m-0 text-lg-start text-center">$28.00</p>
                                                    </div>
                                                </div>
                                                <div className="d-lg-flex gap-2 align-items-center d-none">
                                                    <div className="d-flex gap-1 align-items-center">
                                                        <Icons.Color />
                                                        <span className="fs-14">Black</span>
                                                        <span> | </span>
                                                    </div>
                                                    <div className="d-flex gap-1 align-items-center">
                                                        <Icons.Size />
                                                        <span className="fs-14">2XL</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="d-flex justify-content-between align-items-center mt-3">
                                                <div className="counter-wrapper d-flex bg-white">
                                                    <button className="rounded-circle border-0">&#8722;</button>
                                                    <input type="text" defaultValue={"1"} className="bg-white" />
                                                    <button className="rounded-circle border-0">&#43;</button>
                                                </div>
                                                <div>
                                                    <Link href={""} className="text-decoration-none text-blue">Remove</Link>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <hr className="my-5" />
                                <div>
                                    <form>
                                        <div className="d-flex align-items-end gap-2">
                                            <div className="w-100">
                                                <label htmlFor="exampleInputEmail1" className="form-label">Discount Code</label>
                                                <input type="text" className="form-control rounded-4 p-2" />
                                            </div>
                                            <div>
                                                <button className="btn btn-outline-secondary rounded-pill py-2">Apply</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div className="d-flex justify-content-between mt-4">
                                    <ul className="list-unstyled d-flex flex-column gap-3">
                                        <li className="text-secondary">Subtotal</li>
                                        <li className="text-secondary">Shipping estimate</li>
                                        <li className="text-secondary">Tax estimate</li>
                                        <li className="fw-semibold">Order total</li>
                                    </ul>
                                    <ul className="list-unstyled d-flex flex-column gap-3">
                                        <li className="fw-semibold">$249.00</li>
                                        <li className="fw-semibold">$5.00</li>
                                        <li className="fw-semibold">$24.00</li>
                                        <li className="fw-semibold">$276.00</li>
                                    </ul>
                                </div>
                                <div className="mt-3">
                                    <button className="btn btn-primary rounded-pill fs-6 w-100">Confirm Order</button>
                                    <div className="d-flex gap-2 align-items-center mt-3 justify-content-center">
                                        <Icons.Alert />
                                        <p className="m-0 text-secondary">Learn More <a href={''} className="text-black">Taxes</a> and <a href="" className="text-black"> Shipping </a>information</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

Checkout.getLayout = function getLayout(page: ReactElement) {
    return (
        <RootLayout>
            {page}
        </RootLayout>
    )
}

export default Checkout