import Head from 'next/head'
import { ReactElement } from 'react'
import RootLayout from 'src/layouts/RootLayout'
import ProductCard from 'src/components/ProductCard'
import Hoodie from 'src/assets/images/trending-section-hoddie.png';
import download from 'src/assets/images/download.jpeg';
import download2 from 'src/assets/images/download (1).jpeg';
import download3 from 'src/assets/images/download (2).jpeg';
import download4 from 'src/assets/images/download (3).jpeg';
import download5 from 'src/assets/images/download (4).jpeg';
import Cap from 'src/assets/images/trending-section-cap.png';
import Purse from 'src/assets/images/trending-section-purse.png';
import Minibag from 'src/assets/images/trending-section-mini-bag.png';
import Umbrella from 'src/assets/images/trending-section-umbrela.png';
import Bag2 from 'src/assets/images/trending-section-bag.png';
import sweater from "src/assets/images/new-arrivals-img-1.png";
import shorts from 'src/assets/images/shorts.png';
import Icons from 'src/components/Icons';
import Purse1 from 'src/assets/images/choose-by-expert-purse.png';
import Purse2 from 'src/assets/images/choose-by-expert-purse2.png';
import Purse3 from 'src/assets/images/choose-by-expert-purse3.png';
import Purse4 from 'src/assets/images/choose-by-expert-purse4.png'
import Jacket1 from 'src/assets/images/choose-by-expert-jacket.png';
import Jacket2 from 'src/assets/images/choose-by-expert-jacket2.png';
import Jacket3 from 'src/assets/images/choose-by-expert-jacket3.png';
import Jacket4 from 'src/assets/images/choose-by-expert-jacket4.png';
import Boots from 'src/assets/images/choose-by-expert-shooes.png';
import Boots2 from 'src/assets/images/choose-by-expert-shooes2.png';
import Boots3 from 'src/assets/images/choose-by-expert-shooes3.png';
import Boots4 from 'src/assets/images/choose-by-expert-shooes4.png';
import moneyimg from "src/assets/images/earn-money.png";
import logo from "src/assets/images/logo/logo.svg";
import { Swiper, SwiperSlide } from 'swiper/react';
import { Pagination } from 'swiper/modules';
import 'swiper/css';
import 'swiper/css/pagination';
const Men = () => {
    return (
        <>
            <Head>
                <title>Ciseco | Men</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
                <section className='py-4'>
                    <div className="container">
                        <div className="row">
                            <div className="col-md-6">
                                <h1 className='fw-bold'>Man Collaction</h1>
                                <p className='text-secondary'>We not only help you design exceptional products, but also make it easy for you to share your designs with more like-minded people.</p>
                            </div>
                        </div>
                        <hr />
                        {/* Product-informaction-button *******************************************************/}
                        <div className='d-flex gap-3 pt-3 flex-nowrap product-info-btn overflow-auto flex-md-row align-items-center pb-3'>
                            <div>
                                <button className='trending-button-wrapper btn-outline-secondary rounded-pill pe-3 align-items-center flex-nowrap d-flex gap-2'>
                                    <Icons.Dollar />
                                    <span>1$ - 500$</span>
                                </button>
                            </div>
                            {/* Dropdown-1 */}
                            <div>
                                <button type="button" className="trending-button-wrapper btn-outline-secondary rounded-pill dropdown-toggle align-items-center gap-1 d-flex" data-bs-toggle="dropdown" aria-expanded="false">
                                    <Icons.Celender />
                                    <span>Categories</span>
                                </button>
                                <ul className="dropdown-menu flex-nowrap">
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>Men</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>Women</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>Kids</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>Sports</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            {/* Dropdown-2 */}
                            <div>
                                <button type="button" className="trending-button-wrapper btn-outline-secondary rounded-pill dropdown-toggle align-items-center gap-1 d-flex" data-bs-toggle="dropdown" aria-expanded="false">
                                    <Icons.Paint />
                                    <span>Colors</span>
                                </button>
                                <ul className="dropdown-menu">
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>Black</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>Red</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>White</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            {/* Dropdown-3 */}
                            <div>
                                <button type="button" className="trending-button-wrapper btn-outline-secondary rounded-pill dropdown-toggle align-items-center gap-1 d-flex" data-bs-toggle="dropdown" aria-expanded="false">
                                    <Icons.Size />
                                    <span>Sizes</span>
                                </button>
                                <ul className="dropdown-menu">
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>S</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>M</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>L</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1 btn" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span>XL</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a className="dropdown-item d-flex gap-1 btn btn-link disabled" href="#">
                                            <input type="checkbox" id="checkbox" name="checkbox" />
                                            <span className='text-decoration-line-through'>XXL</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div>
                                <button className='trending-button-wrapper btn-outline-secondary rounded-pill align-items-center d-flex gap-2'>
                                    <Icons.Discount />
                                    <span>On Sale</span>
                                </button>
                            </div>
                        </div>
                        <div className="row gy-4 justify-content-md-center justify-content-start ">
                            <div className="col-sm-6 col-md-4 col-lg-3" id='arrivals'>
                                <div className='text-center'>
                                    {/* Card-1 ***********/}
                                    <ProductCard
                                        outerimg={Hoodie.src}
                                        innerimg1={download.src}
                                        innerimg2={download2.src}
                                        innerimg3={download3.src}
                                        innerimg4={download4.src}
                                        innerimg5={download5.src}
                                        title="Leather Gloves"
                                        subtitle="Perfect Mint Green"
                                        price="$82.00"
                                        review="4.7 (35 Reviews)"
                                        starticon={<Icons.Star />}
                                    />
                                </div>
                            </div>
                            <div className="col-sm-6 col-md-4 col-lg-3" id='arrivals'>
                                <div className='text-center'>
                                    {/* Card-2 ***********/}
                                    <ProductCard
                                        outerimg={Bag2.src}
                                        innerimg1={download.src}
                                        innerimg2={download2.src}
                                        innerimg3={download3.src}
                                        innerimg4={download4.src}
                                        innerimg5={download5.src}
                                        title="Leather Gloves"
                                        subtitle="Perfect Mint Green"
                                        price="$82.00"
                                        review="4.7 (35 Reviews)"
                                        starticon={<Icons.Star />}
                                    />
                                </div>
                            </div>
                            <div className="col-sm-6 col-md-4 col-lg-3" id='arrivals'>
                                <div className='text-center'>
                                    {/* Card-3 ***********/}
                                    <ProductCard
                                        outerimg={Cap.src}
                                        innerimg1={download.src}
                                        innerimg2={download2.src}
                                        innerimg3={download3.src}
                                        innerimg4={download4.src}
                                        innerimg5={download5.src}
                                        title="Leather Gloves"
                                        subtitle="Perfect Mint Green"
                                        price="$82.00"
                                        review="4.7 (35 Reviews)"
                                        starticon={<Icons.Star />}
                                    />
                                </div>
                            </div>
                            <div className="col-sm-6 col-md-4 col-lg-3" id='arrivals'>
                                <div className='text-center'>
                                    {/* Card-4 ***********/}
                                    <ProductCard
                                        outerimg={Purse.src}
                                        innerimg1={download.src}
                                        innerimg2={download2.src}
                                        innerimg3={download3.src}
                                        innerimg4={download4.src}
                                        innerimg5={download5.src}
                                        title="Leather Gloves"
                                        subtitle="Perfect Mint Green"
                                        price="$82.00"
                                        review="4.7 (35 Reviews)"
                                        starticon={<Icons.Star />}
                                    />
                                </div>
                            </div>
                            <div className="col-sm-6 col-md-4 col-lg-3" id='arrivals'>
                                <div className='text-center'>
                                    {/* Card-5 ***********/}
                                    <ProductCard
                                        outerimg={sweater.src}
                                        innerimg1={download.src}
                                        innerimg2={download2.src}
                                        innerimg3={download3.src}
                                        innerimg4={download4.src}
                                        innerimg5={download5.src}
                                        title="Leather Gloves"
                                        subtitle="Perfect Mint Green"
                                        price="$82.00"
                                        review="4.7 (35 Reviews)"
                                        starticon={<Icons.Star />}
                                    />
                                </div>
                            </div>
                            <div className="col-sm-6 col-md-4 col-lg-3" id='arrivals'>
                                <div className='text-center'>
                                    {/* Card-6 ***********/}
                                    <ProductCard
                                        outerimg={Umbrella.src}
                                        innerimg1={download.src}
                                        innerimg2={download2.src}
                                        innerimg3={download3.src}
                                        innerimg4={download4.src}
                                        innerimg5={download5.src}
                                        title="Leather Gloves"
                                        subtitle="Perfect Mint Green"
                                        price="$82.00"
                                        review="4.7 (35 Reviews)"
                                        starticon={<Icons.Star />}
                                    />
                                </div>
                            </div>
                            <div className="col-sm-6 col-md-4 col-lg-3" id='arrivals'>
                                <div className='text-center'>
                                    {/* Card-7 ***********/}
                                    <ProductCard
                                        outerimg={Minibag.src}
                                        innerimg1={download.src}
                                        innerimg2={download2.src}
                                        innerimg3={download3.src}
                                        innerimg4={download4.src}
                                        innerimg5={download5.src}
                                        title="Leather Gloves"
                                        subtitle="Perfect Mint Green"
                                        price="$82.00"
                                        review="4.7 (35 Reviews)"
                                        starticon={<Icons.Star />}
                                    />
                                </div>
                            </div>
                            <div className="col-sm-6 col-md-4 col-lg-3" id='arrivals'>
                                <div className='text-center'>
                                    {/* Card-8 ***********/}
                                    <ProductCard
                                        outerimg={shorts.src}
                                        innerimg1={download.src}
                                        innerimg2={download2.src}
                                        innerimg3={download3.src}
                                        innerimg4={download4.src}
                                        innerimg5={download5.src}
                                        title="Leather Gloves"
                                        subtitle="Perfect Mint Green"
                                        price="$82.00"
                                        review="4.7 (35 Reviews)"
                                        starticon={<Icons.Star />}
                                    />
                                </div>
                            </div>
                        </div>
                        <div className='row justify-content-between mt-4 align-items-center'>
                            <div className='col-md-6'>
                                <div className='pb-3'>
                                    <nav aria-label="...">
                                        <ul className="pagination pagination-sm d-flex gap-3 justify-content-center justify-content-md-start m-0">
                                            <li className="page-item active" aria-current="page">
                                                <span className="page-link">1</span>
                                            </li>
                                            <li className="page-item"><button className="page-link">2</button></li>
                                            <li className="page-item"><button className="page-link">3</button></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div className='col-md-6'>
                                <div className='text-center text-md-end'>
                                    <button className='rounded-pill btn btn-primary fs-6 '>Show Me More</button>
                                </div>
                            </div>
                        </div>
                        <hr className='my-5' />
                        <Swiper
                            spaceBetween={20}
                            modules={[Pagination]}
                            className="mySwiper"
                            breakpoints={{
                                0: {
                                    slidesPerView: 1,
                                    spaceBetween: 20,
                                },
                                575: {
                                    slidesPerView: 1,
                                    spaceBetween: 20,
                                },
                                768: {
                                    slidesPerView: 2,
                                    spaceBetween: 40,
                                },
                                992: {
                                    slidesPerView: 3,
                                    spaceBetween: 40,
                                },
                                1200: {
                                    slidesPerView: 3,
                                    spaceBetween: 20,
                                },
                            }}
                        >
                            <SwiperSlide>
                                {/* Card-1 */}
                                <div className="our-expert-img-wrapper choosen-bg-color rounded-3 text-center">
                                    <img src={Jacket1.src} alt="sweater" className='img-fluid' />
                                </div>
                                <div className='row pt-2'>
                                    {/* inner-card-1 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color rounded-3'>
                                            <img src={Jacket2.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                    {/* inner-card-2 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color rounded-3'>
                                            <img src={Jacket3.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                    {/* inner-card-3 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color rounded-3'>
                                            <img src={Jacket4.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                </div>
                                <div className="row align-items-center pt-3">
                                    <div className="col-md-6">
                                        <p className='m-0 fw-bold'> Bomber Jacket</p>
                                    </div>
                                    <div className="col-md-6">
                                        <div className='text-end'>
                                            <span className='fs-14 text-green fw-bold'>$42.00</span>
                                        </div>
                                    </div>
                                    <div className='col-md-12'>
                                        <div className='text-secondary align-items-center d-flex gap-1 fs-14'>
                                            <span>Orange |</span>
                                            <Icons.Star />
                                            <span className='text-secondary fs-14'>4.9 (245 Reviews)</span>
                                        </div>
                                    </div>
                                </div>
                            </SwiperSlide>
                            <SwiperSlide>
                                {/* Card-2 */}
                                <div className="our-expert-img-wrapper text-center choosen-bg-color rounded-3">
                                    <img src={Purse1.src} alt="sweater" className='img-fluid' />
                                </div>
                                <div className='row pt-2'>
                                    {/* inner-card-1 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color  rounded-3'>
                                            <img src={Purse2.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                    {/* inner-card-2 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color rounded-3'>
                                            <img src={Purse3.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                    {/* inner-card-3 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color rounded-3'>
                                            <img src={Purse4.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                </div>
                                <div className="row align-items-center pt-3">
                                    <div className="col-md-6">
                                        <p className='m-0 fw-bold'> Bomber Jacket</p>
                                    </div>
                                    <div className="col-md-6">
                                        <div className='text-end'>
                                            <span className='fs-14 text-green fw-bold'>$42.00</span>
                                        </div>
                                    </div>
                                    <div className='col-md-12'>
                                        <div className='text-secondary align-items-center d-flex gap-1 fs-14'>
                                            <span>Orange |</span>
                                            <Icons.Star />
                                            <span className='text-secondary fs-14'>4.9 (245 Reviews)</span>
                                        </div>
                                    </div>
                                </div>
                            </SwiperSlide>
                            <SwiperSlide>
                                {/* Card-3 */}
                                <div className="our-expert-img-wrapper text-center choosen-bg-color rounded-3">
                                    <img src={Boots.src} alt="sweater" className='img-fluid' />
                                </div>
                                <div className='row pt-2'>
                                    {/* inner-card-1 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color rounded-3'>
                                            <img src={Boots2.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                    {/* inner-card-2 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color rounded-3'>
                                            <img src={Boots3.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                    {/* inner-card-3 */}
                                    <div className="col-4">
                                        <div className='choosen-bg-color rounded-3'>
                                            <img src={Boots4.src} alt="sweater" className='img-fluid' />
                                        </div>
                                    </div>
                                </div>
                                <div className="row align-items-center pt-3">
                                    <div className="col-md-6">
                                        <p className='m-0 fw-bold'> Bomber Jacket</p>
                                    </div>
                                    <div className="col-md-6">
                                        <div className='text-end'>
                                            <span className='fs-14 text-green fw-bold'>$42.00</span>
                                        </div>
                                    </div>
                                    <div className='col-md-12'>
                                        <div className='text-secondary align-items-center d-flex gap-1 fs-14'>
                                            <span>Orange |</span>
                                            <Icons.Star />
                                            <span className='text-secondary fs-14'>4.9 (245 Reviews)</span>
                                        </div>
                                    </div>
                                </div>
                            </SwiperSlide>
                            <SwiperSlide>
                                <div className='choosen-bg-color rounded-3 h-410 align-items-center text-center justify-content-center d-flex'>
                                    <div className='justify-content-center'>
                                        <h5 className='m-0 fw-bold align-items-center'>
                                            <span>More Items</span>
                                            <Icons.Rigtharrow />
                                        </h5>
                                        <p className='m-0 fs-14'>Show Me More</p>
                                    </div>
                                </div>
                            </SwiperSlide>
                        </Swiper>
                        <hr className='my-5' />
                        <div className="row align-items-center">
                            <div className="col-md-6 order-2 order-md-1">
                                <div className='text-center text-md-start pt-3'>
                                    <a href='/' className="logo">
                                        <img src={logo.src} alt="logo" className='logo-wrapper img-fluid' />
                                    </a>
                                    {/* Left-side */}
                                    <div className='content pt-3'>
                                        <h2 className='fw-bold text-primary'>Earn free money with Ciseco</h2>
                                        <p className='text-secondary py-3'>With Ciseco you will get freeship & savings combo...</p>
                                        <div className='d-flex gap-3 flex-column flex-md-row text-center text-md-start pb-3'>
                                            <div>
                                                <button className='btn btn-primary rounded-pill btn-lg
                                                '>Savings combo</button>
                                            </div>
                                            <div>
                                                <button className='btn btn-success rounded-pill btn-lg'>Discover more</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-md-6 order-1 order-md-1">
                                <img src={moneyimg.src} alt="moneyimg" className='img-fluid' />
                            </div>
                        </div>
                    </div>
                </section>
            </main >
        </>
    )
}

Men.getLayout = function getLayout(page: ReactElement) {
    return (
        <RootLayout>
            {page}
        </RootLayout>
    )
}

export default Men