import Head from 'next/head'
import RootLayout from '@/layouts/RootLayout'
import { ReactElement } from 'react'
import logo from "../assets/images/logo/logo.svg";
import moneyimg from "../assets/images/earn-money.png";
const Women = () => {
  return (
    <>
      <Head>
        <title>Ciseco | Women</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <section className='py-4'>
          <div className="container">
            <div className="row align-items-center">
              <div className="col-md-6 order-2 order-md-1">
                <div className='text-center text-md-start pt-3'>
                  <a href='/' className="logo">
                    <img src={logo.src} alt="logo" className='logo-wrapper img-fluid' />
                  </a>
                  {/* Left-side */}
                  <div className='content pt-3'>
                    <h2 className='fw-bold text-primary'>Earn free money with Ciseco</h2>
                    <p className='text-secondary py-3'>With Ciseco you will get freeship & savings combo...</p>
                    <div className='d-flex gap-3 flex-column flex-md-row text-center text-md-start pb-3'>
                      <div>
                        <button className='btn btn-primary rounded-pill btn-lg'>Savings combo</button>
                      </div>
                      <div>
                        <button className='btn btn-success rounded-pill btn-lg'>Discover more</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-6 order-1 order-md-1">
                <img src={moneyimg.src} alt="moneyimg" className='img-fluid' />
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}


Women.getLayout = function getLayout(page: ReactElement) {
  return (
    <RootLayout>
      {page}
    </RootLayout>
  )
}

export default Women