enum OrderStatus {
  PLACED = "PLACED",
  PAID = "PAID",
  SHIPPED = "SHIPPED",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  DELIVERED = "DELIVERED",
  DISPUTE = "DISPUTE",
  RETURNED = "RETURNED",
  REFUND_IN_PROGESS = "REFUND_IN_PROGESS",
  REFUNDED = "REFUNDED",
  CANCELLECTION_PENDING = "PENDING_CANCELLATION",
}
enum Products {
  CATEGORY = "CATEGORY",
  SUB_CATEGORY = "SUB_CATEGORY",
  SUB_SUB_CATEGORIES = "SUB_SUB_CATEGORIES",
  PRODUCTS = "PRODUCTS",
}
enum Language {
  ARABIC = "ARABIC",
  ENGLISH = "ENGLISH",
}
enum Order {
  ORDER_CREATED = "ORDER_CREATED",
}
export default {
  OrderStatus,
  Products,
  Language,
  Order,
};
