import React, { ReactElement, useRef, useState } from 'react';
import Head from 'next/head';
import PrivacyPolicy from "@/assets/images/privacy-policy.jpg";
import RootLayout from 'src/layouts/RootLayout';
const Privacy = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <section className='py-5'>
                <div className="container bg-white shadow p-4 p-md-5 rounded-4">
                    <div className="row">
                        <div className="col-md-12">
                            <div className='text-center'>
                                <h1 className='fw-bold'>Privacy Policy</h1>
                            </div>
                            <div className='my-3'>
                                <img src={PrivacyPolicy.src} className='w-100 rounded-3 object-fit-cover border' height={400} alt="privacy"/>
                            </div>
                            <div className='text-center text-md-start'>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Labore ex, autem veniam odio eum laboriosam. Soluta dolorem eos aut enim delectus accusamus doloribus minus reprehenderit temporibus, repellendus dolores perspiciatis cumque recusandae earum dignissimos totam id placeat debitis hic impedit sunt! Est earum rerum voluptatem facere incidunt numquam iure voluptate quod repellat! Et obcaecati fugiat repellat aliquam suscipit! Cupiditate nulla, expedita maiores dolor quibusdam, molestiae, recusandae voluptates inventore quidem officiis reprehenderit voluptatum! Esse rem earum ducimus sequi repellat, facere deleniti minus veniam inventore ab distinctio maxime laudantium eos quod tempore cupiditate enim, labore quos mollitia fuga? Animi in possimus nisi deleniti, eaque enim obcaecati autem quidem explicabo error nostrum quis sint nobis eius consectetur tempore quisquam labore similique fuga quaerat dolorum! In eum distinctio placeat laboriosam minima adipisci, nobis quaerat voluptas voluptatum. Accusamus ad eaque sequi ipsa accusantium doloribus adipisci. Eius quasi reiciendis non necessitatibus nihil dolore recusandae accusantium enim quo vitae eos fuga ipsam mollitia odio dolorum vel repudiandae magnam debitis, rerum corrupti. Dolor deleniti magni eligendi iure nemo omnis unde laudantium dolore quo? Ex qui nam provident cupiditate quaerat aspernatur sapiente beatae harum exercitationem fugiat, magnam itaque ea suscipit laboriosam dicta velit placeat quis nesciunt enim incidunt corporis cumque laudantium tenetur! Nemo praesentium atque ducimus autem sit ipsum architecto aliquam. Doloribus distinctio, sint vero similique unde molestiae, consequatur quasi numquam ex soluta ea! Itaque, maiores culpa. Unde quia cupiditate vitae quaerat nihil reprehenderit itaque numquam voluptatibus animi, tempore Aboutconsequatur incidunt ut accusamus repellendus provident dolorum impedit. Atque, necessitatibus! Dolore, necessitatibus? Amet veritatis rem assumenda sapiente ad consectetur eligendi, maiores dolores reprehenderit fuga reiciendis expedita beatae animi aliquid consequatur itaque sed deserunt molestias esse vitae. Debitis tempora laboriosam tempore possimus neque laborum aperiam aliquid, voluptas fugit blanditiis nesciunt harum atque nostrum cumque cupiditate at velit, porro minus ex! At nihil sapiente veritatis praesentium perferendis. A voluptatem aut doloremque eos, corrupti nobis quisquam illo, deserunt aperiam, tempore exercitationem. Incidunt architecto necessitatibus qui iste alias tenetur molestiae quibusdam ut optio suscipit recusandae maxime accusantium porro, corrupti ullam ipsa in officiis vel placeat neque blanditiis, aliquam vero. Hic ea sunt, asperiores consectetur quis incidunt sequi deserunt est porro iure quos minus ab error pariatur commodi amet nesciunt nam accusantium facilis minima, sit inventore optio! Quae dolore maiores nemo maxime repudiandae suscipit, sapiente consectetur reprehenderit iusto quo nisi cumque incidunt cupiditate quasi aliquam animi saepe excepturi? Provident nihil omnis aliquid blanditiis possimus similique expedita.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}

Privacy.getLayout = function getLayout(page: ReactElement) {
    return (
        <RootLayout>
            {page}
        </RootLayout>
    )
}

export default Privacy
